### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by HarleyQuinn36** [Enum0x539/Qvoid-Token-Grabber#12]
Not sure where I am meant to put my webshook too

**Comment by Enum0x539** [comment]
[/Qvoid Token Grabber/Main/Settings.cs](https://github.com/Enum0x539/Qvoid-Token-Grabber/blob/main/Qvoid%20Token%20Grabber/Qvoid%20Token%20Grabber/Main/Settings.cs)

**Comment by HarleyQuinn36** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS2012	Cannot open 'C:\Users\\OneDrive\Desktop\Qvoid-Token-Grabber-main\Qvoid Token Grabber\Qvoid Token Grabber\obj\Release\Qvoid Token Grabber.exe' for writing -- 'Access to the path 'C:\Users\\OneDrive\Desktop\Qvoid-Token-Grabber-main\Qvoid Token Grabber\Qvoid Token Grabber\obj\Release\Qvoid Token Grabber.exe' is denied.'	Qvoid Token Grabber	C:\Users\\OneDrive\Desktop\Qvoid-Token-Grabber-main\Qvoid Token Grabber\Qvoid Token Grabber\CSC	1	Active

just getting this when building it now using vs 2022

**Comment by Enum0x539** [comment]
Disable your anti-virus.
