### ISSUE TITLE
no data

### ISSUE THREAD

**Issue by Therealloli101** [Enum0x539/Qvoid-Token-Grabber#17]
i ran it myself, my targets ran it and nothing, no data was send to the webhook

**Comment by Enum0x539** [comment]
Can be caused due to so many reasons ...

Check if your anti-virus is disabled.
What builds of Discord you have installed?
What browsers you have installed?
You getting any error while debugging?
What version of Windows you using?

**Comment by Therealloli101** [comment]
Av is disabled
Discord is up to date
Browser is OperaGX
No errors while debugging
Windows 10 Pro

**Comment by Enum0x539** [comment]
Put breakpoint on line 491 (Main/Grabber.cs) and check if it reach there.

**Comment by Enum0x539** [comment]
Alright since I will archive this project in couple of days and you have not responded, I will close this issue.
