### ISSUE TITLE
Built EXE, ran it, no data sent.

### ISSUE THREAD

**Issue by NightTabGit** [Enum0x539/Qvoid-Token-Grabber#18]
Replaced line in Settings.cs with discord API.

When running through VS, sends information fine to webhook.

When built into an exe, does not work at all. Process starts, seen in Task Manager, then closes.

**Comment by Enum0x539** [comment]
There is a filter system, if the credentials of the new grab is the same as the previous it won't send it again in order to prevent spam.

**Comment by NightTabGit** [comment]
Where does it store the last grab? As Ive rebuilt multiple times, and deleted the last messages, and it wont resend.

**Comment by Enum0x539** [comment]
C:\\Users\\UR_USER\\d0060d24-c4a5-480f-803a-ec978344350d.dat delete this file and try again.

**Comment by NightTabGit** [comment]
Great! Much help!
