### ISSUE TITLE
After Build Exe not working

### ISSUE THREAD

**Issue by AmandaL1991** [Enum0x539/Qvoid-Token-Grabber#22]
i am building exe after build run exe not working no grabbing any data and not show in discord channel

**Comment by Enum0x539** [comment]
Answer my questions if you can (or ask the one who it didn't worked for him):
1) What browsers you have installed?
2) What distribute of Windows you using?
3) What build of Discord you using (if you have couple so all of them)?
4) You have betterdiscord installed?
5) Is your anti-virus disabled?

**Comment by Enum0x539** [comment]
I have found the problem, I will fix it asap.

**Comment by Breadwastakenbyme** [comment]
any update on the exe not working I am very interested?

**Comment by AmandaL1991** [comment]
I am fix this problem exe working fine

**Comment by AmandaL1991** [comment]
@Enum0x539 Currently Data Grabber Bot using your bot how to use own bot

**Comment by Enum0x539** [comment]
> @Enum0x539 Currently Data Grabber Bot using your bot how to use own bot 

I didn't understand you
