### ISSUE TITLE
Not Work

### ISSUE THREAD

**Issue by SergioCupido** [Enum0x539/Qvoid-Token-Grabber#24]
![image](https://user-images.githubusercontent.com/97339303/157436658-948de531-1eed-468c-a9b7-78084868d094.png)

**Comment by Enum0x539** [comment]
Can u send the full screenshot?

**Comment by gameingkwkw** [comment]
Not sure but this might help
In the path search
C:%Username%\UR_USER\d0060d24-c4a5-480f-803a-ec978344350d.dat
Shit + del it and might help.

**Comment by Enum0x539** [comment]
This is the filter file, so it should of worked for the first time...
