### ISSUE TITLE
how to work this? the youtube video got taken down

### ISSUE THREAD

**Issue by coryxninja1** [Enum0x539/Qvoid-Token-Grabber#27]
idk can u like make a text file or something explaining how it works

**Comment by Enum0x539** [comment]
I'll post a new tutorial soon.
But search on YouTube there is a video that someone made on how to build it using the source.

**Comment by lolipopsk2** [comment]
> idk can u like make a text file or something explaining how it works

https://www.youtube.com/watch?v=NOyTDNuZbCQ
