### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Paradox222** [Enum0x539/Qvoid-Token-Grabber#29]
i dont receive the info in webhook

**Comment by XxDarknedxX** [comment]
same

**Comment by Enum0x539** [comment]
I will check it again but next time if you can so describe everything you know about the bug, as a result it will be patched much faster.

**Comment by Enum0x539** [comment]
So I rechecked, for me everything works as it should.
Try to debug the project and tell me if you get errors and if you do where exactly (File, Line, Screenshot).

**Comment by carbomfiber** [comment]
Nice grabber. DONT DOWNLOAD OR RUN it automatic grabs all your details

**Comment by Enum0x539** [comment]
@carbomfiber you are pretty stupid so keep writing on your own issue that you have opened and I will roast every word you will say because you are little kid who probably saw hackers on the TV and became Ethical hacker :D

**Comment by carbomfiber** [comment]
Well if i’m wrong and a small kid who saw hackers on the tv then why did you delete my comment?

**Comment by carbomfiber** [comment]
Never mind people can use it if they want lol

**Comment by Enum0x539** [comment]
> Never mind people can use it if they want lol

And for some reason you didn't reply my comment on the issue you opened

**Comment by carbomfiber** [comment]
Why should I reply?

**Comment by carbomfiber** [comment]
+1 for most toxic person👍  Have a great day I won’t comment on any of your replies anymore because it’s useless🤓

**Comment by Enum0x539** [comment]
> Why should I reply?

Because if someone told some words against your words you need to further prove your point but alright I forgive you because you are little kid.

**Comment by SadraKhorami** [comment]
> @carbomfiber you are pretty stupid so keep writing on your own issue that you have opened and I will roast every word you will say because you are little kid who probably saw hackers on the TV and became Ethical hacker :D

fact 😂👍🏽

**Comment by SadraKhorami** [comment]
> +1 for most toxic person👍 Have a great day I won’t comment on any of your replies anymore because it’s useless🤓

yeah, it's useless to argue with damn kids like you who have very little knowledge. 🤓

**Comment by XxDarknedxX** [comment]
> > +1 for most toxic person👍 Have a great day I won’t comment on any of your replies anymore because it’s useless🤓
> 
> yeah, it's useless to argue with damn kids like you who have very little knowledge. 🤓

I totally agree that's right oh my god how i didn't realize this earlier @Enum0x539 you should give a fuck about this motherfucking RIGHT NOW!!!

**Comment by XxDarknedxX** [comment]
Also it's literally open source can't y'all just compilie it from visual studio or y'all just unable to do this 🤓🤓🤓🤓
![Uploading Screenshot_2022-06-06-11-44-53-72_e307a3f9df9f380ebaf106e1dc980bb6.jpg…]()

**Comment by Enum0x539** [comment]
I released new update try it now.

**Comment by Relexcode** [comment]
It does work try clicking the run button

**Comment by Enum0x539** [comment]
No further comment, closed.
