### ISSUE TITLE
No data sent to webhook

### ISSUE THREAD

**Issue by Leyahc** [Enum0x539/Qvoid-Token-Grabber#3]
I ran the compiled end product but it did not send any data to the webhook I set in the settings.cs but It did drop files in the \AppData\Local\Temp\ Folder. Am I doing something wrong? Or is the issue in the code?

**Comment by Enum0x539** [comment]
Hi Leyahc,
Check if this file exists C:\Users\ {UR_USERNAME} \d0060d24-c4a5-480f-803a-ec978344350d.dat

**Comment by Enum0x539** [comment]
No response ... closing.
