### ISSUE TITLE
FAKE DONT DOWNLOAD

### ISSUE THREAD

**Issue by carbomfiber** [Enum0x539/Qvoid-Token-Grabber#31]
Nice grabber. DONT DOWNLOAD OR RUN it automatic grabs all your details

**Comment by skies-s** [comment]
How so

**Comment by carbomfiber** [comment]
Like I wrote. It steals you discord token. When I run the file then it logged me out of discord and that is a sign of that they try to grab your discord token

**Comment by skies-s** [comment]
Hmm, whats ur discord

**Comment by Enum0x539** [comment]
> Like I wrote. It steals you discord token. When I run the file then it logged me out of discord and that is a sign of that they try to grab your discord token

Are you fucking stupid or something?
You opened the stealer file and you expect it to not steal your stuff? btw if you didn't fill the webhook no one receive the data.

As for the rest the code is fully open source :D you can view each part of the code and with little programming skills (I'm not talking about all the **fake* Python, HTML, PHP CSS AND JS "coders") you can understand how exactly it works step by step (this is the purpose of this project if you have read the README file) and even see that I don't steal any data myself!
Have a nice day little skid.
I'll leave this "issue" opened for people to see it and learn from your stupidity.

**Comment by skies-s** [comment]
> > Like I wrote. It steals you discord token. When I run the file then it logged me out of discord and that is a sign of that they try to grab your discord token
> 
> Are you fucking stupid or something? You opened the stealer file and you expect it to not steal your stuff? btw if you didn't fill the webhook no one receive the data.
> 
> As for the rest the code is fully open source :D you can view each part of the code and with little programming skills (I'm not talking about all the *_fake_ Python, HTML, PHP CSS AND JS "coders") you can understand how exactly it works step by step (this is the purpose of this project if you have read the README file) and even see that I don't steal any data myself! Have a nice day little skid. I'll leave this "issue" opened for people to see it and learn from your stupidity.

U got a point ig, but ur grabber paths r fucked up nigga, it doesnt even give the token from the discord app. fix it first soyboy loudmouth
![image](https://user-images.githubusercontent.com/68137719/167789228-64acb3bc-354e-4e10-ad5a-ed47ca5449d4.png)

**Comment by Enum0x539** [comment]
> > > Like I wrote. It steals you discord token. When I run the file then it logged me out of discord and that is a sign of that they try to grab your discord token
> 
> > 
> 
> > Are you fucking stupid or something? You opened the stealer file and you expect it to not steal your stuff? btw if you didn't fill the webhook no one receive the data.
> 
> > 
> 
> > As for the rest the code is fully open source :D you can view each part of the code and with little programming skills (I'm not talking about all the *_fake_ Python, HTML, PHP CSS AND JS "coders") you can understand how exactly it works step by step (this is the purpose of this project if you have read the README file) and even see that I don't steal any data myself! Have a nice day little skid. I'll leave this "issue" opened for people to see it and learn from your stupidity.
> 
> 
> 
> U got a point ig, but ur grabber paths r fucked up nigga, it doesnt even give the token from the discord app. fix it first soyboy loudmouth
> 
> ![image](https://user-images.githubusercontent.com/68137719/167789228-64acb3bc-354e-4e10-ad5a-ed47ca5449d4.png)
> 
> 

So if something is not working for you open an issue with the right format and I will fix it asap.

**Comment by custom1337** [comment]
> 

absolute fucking gigachad
