### ISSUE TITLE
No Content Get Sent To The Webhook

### ISSUE THREAD

**Issue by tanukieggs** [Enum0x539/Qvoid-Token-Grabber#33]
Hello, I'm unsure if theres anything I'm doing wrong, but, went I open the builder, and put in my webhook, Nothing gets sent to my webhook when I run the grabber. I recorded all of the steps I did to make this happen, so if you want, watch the video to see if I may have done something wrong
https://user-images.githubusercontent.com/105336066/173463358-5d97e3e5-a35c-4670-ab77-50f8bb4d0219.mp4

**Comment by redbaron2k7** [comment]
Yeah I have the same issue

**Comment by Enum0x539** [comment]
Hello,
Please ensure that your anti-virus is turned off and there is nothing that can interrupt the process.
Do not run it twice since it might cause issues.

If the problem is still happening, check if this file -> "C:\\Users\\UR_USER\\something_weird.dat" exists if it does delete it.
I will add advance diagnose for the builder asap.

**Comment by redbaron2k7** [comment]
> 

Alright but what if someone else that you send it to runs it multiple times?

**Comment by redbaron2k7** [comment]
Also I followed all these steps and my antivirus is already off and that file does not exist

**Comment by Enum0x539** [comment]
> Also I followed all these steps and my antivirus is already off and that file does not exist

Can you install an IDE such as Visual Studio and debug the code and tell me where it stops / where error occurs ?

**Comment by redbaron2k7** [comment]
I have visual studio installed already but how do I do that?

**Comment by Enum0x539** [comment]
Ah u have a background in coding? if u do so put a breakpoints in critical points and see if the program reaches there.

**Comment by tanukieggs** [comment]
> Hello, Please ensure that your anti-virus is turned off and there is nothing that can interrupt the process. Do not run it twice since it might cause issues.
> 
> If the problem is still happening, check if this file -> "C:\Users\UR_USER\something_weird.dat" exists if it does delete it. I will add advance diagnose for the builder asap.

hi, this might seem like a dumb question, but, I have my antivirus turned off, yet when i run the diagnose, it says its on still. Anyway to turn it off completely?
![unknown](https://user-images.githubusercontent.com/105336066/173659478-e6d4f7d7-5b94-4c3b-aa37-b67ab03113c8.png)

**Comment by Enum0x539** [comment]
It only checking if the av exists, anyway I changed the settings try now.

**Comment by tanukieggs** [comment]
I'm unsure if I'm running the source code incorrectly, but, when i try to build it, nothing happens again? Is there something I'm doing wrong?

https://user-images.githubusercontent.com/105336066/174455979-fd2511e7-fe86-4a6b-bde0-b7ca4b57ed78.mp4

**Comment by Enum0x539** [comment]
> I'm unsure if I'm running the source code incorrectly, but, when i try to build it, nothing happens again? Is there something I'm doing wrong?
> unknown_2022.06.18-16.18_Trim.mp4

Yes, it's not working with ptb / canary webhooks.

**Comment by Enum0x539** [comment]
> > I'm unsure if I'm running the source code incorrectly, but, when i try to build it, nothing happens again? Is there something I'm doing wrong?
> > unknown_2022.06.18-16.18_Trim.mp4
> 
> Yes, it's not working with ptb / canary webhooks.

It's was the problem, fixed.
closed.
