### ISSUE TITLE
Give exe

### ISSUE THREAD

**Issue by KkjusTkk7074** [Enum0x539/Qvoid-Token-Grabber#4]
Please build it and give exe

**Comment by Enum0x539** [comment]
Hi KkjusTkk7074,
I cannot build it and give you the EXE because, This is not "grabber builder" it's just the grabber meaning you will need to put your webhook and compile 😄 .

**Comment by Enum0x539** [comment]
Well you have build option but I think it will be much easier to checkout on YouTube or something.
